### ISSUE TITLE
Unhandled errors on loading the app

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/accounts-app#112]
Since last few releases, we are observing multiple instance of following error in console. Though they does not seem to do any significant harm right now, it is better to handle it by identifying the root cause of it and fixing it.
<pre>
app.c20966f….js:sourcemap:438 Error: transition prevented
    at L [as $get] (app.c20966f….js:sourcemap:23)
    at Object.a [as invoke] (app.c20966f….js:sourcemap:436)
    at app.c20966f….js:sourcemap:436
    at n (app.c20966f….js:sourcemap:436)
    at r (app.c20966f….js:sourcemap:436)
    at Object.a [as invoke] (app.c20966f….js:sourcemap:436)
    at app.c20966f….js:sourcemap:436
    at c (app.c20966f….js:sourcemap:436)
    at le (app.c20966f….js:sourcemap:436)
    at a (app.c20966f….js:sourcemap:436) "Possibly unhandled rejection: {}"
</pre>

**Comment by vikasrohit** [comment]
@dmessing @ajefts @fnisen @sudoster @ykohata fyi

**Comment by vikasrohit** [comment]
The root cause is the angular release update starting 1.5.8. Seems like ui-router's code is causing these errors. More information can be found [here](https://github.com/angular-ui/ui-router/issues/2889).

Fix is to upgrade the ui-router dependency to 1.x release as suggested [here](https://github.com/angular-ui/ui-router/issues/2889#issuecomment-258294902).

**Comment by vikasrohit** [comment]
PR #113 created for the same. @ykohata it would be great if you can review the changes.

**Comment by fnisen** [comment]
@vikasrohit looks like Kohata-san reviewed. Can we close this?

**Comment by vikasrohit** [comment]
@fnisen With these changes, there is still some warnings when we install dependencies using npm. I am trying to get rid of them as well.

**Comment by vikasrohit** [comment]
Done with those changes as well. It should be good now. I will merge it before we deploy accounts-app to prod.

**Comment by fnisen** [comment]
Beautiful, thanks!
