### ISSUE TITLE
Enable multiple sso providers

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/accounts-app#123]
Currently, we're only handling wipro adfs from the front end.  We need to support any sso provider that we have configured.

Based on the domain, the appropriate sso provider should be used.  If this will take more than a day, let's start by enabling wipro adfs as well as our sfdc.

**Comment by vikasrohit** [comment]
Now two providers supported: `wipro-adfs` (for all email/adid containing `@wipro`) and `sfdc-aspdev` (for all email/adid containing `@asp.appirio.com`)

**Comment by vikasrohit** [comment]
@ajefts Do we need any thing else to close this one?

**Comment by vikasrohit** [comment]
Closing to clean up.
