### ISSUE TITLE
Same message being shown for sso and non sso users after registration

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/accounts-app#133]
Same message `Thanks for joining Topcoder.` is being rendered for both sso and non sso users after successful registration.

**Comment by vikasrohit** [comment]
@ajefts fyi

**Comment by vikasrohit** [comment]
Fixed in https://github.com/appirio-tech/accounts-app/tree/hotfix/same-msg-for-sso-non-sso-register

**Comment by ajefts** [comment]
@vikasrohit Looks like the page is blank still...at least for SSO reg success...

**Comment by vikasrohit** [comment]
Ohk. Let me reproduce it by following full flow.

**Comment by vikasrohit** [comment]
It was not reproducible on on local, but could reproduce it on dev. Seems link inline controllers in state configuration for ui-router were causing the troubles. Fixed now.

**Comment by vikasrohit** [comment]
Closing to clean up.
