### ISSUE TITLE
Error state of form elements is not visible

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/accounts-app#151]
<img width="544" alt="screen shot 2017-08-02 at 12 42 28 pm" src="https://user-images.githubusercontent.com/2417632/28861816-3bce4d5e-7780-11e7-8fb5-b512f4377e7a.png">

fyi @fnisen @vic-topcoder

**Comment by vikasrohit** [comment]
Done. @fnisen I haven't added error class to the password field because it was giving me wrong UX as a user. We are showing validation errors(or status) in tooltip for password field, so I guess we can avoid adding error class for password field. However, if you still think it would be good to have error class on password field, I can add it.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Yes, this is the right approach--we don't need the error class on password field because the user should never end up in an error state; the validation is already showing them that they haven't filled out the form as needed.
