### ISSUE TITLE
Show password button is misplaced on member side reset password page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/accounts-app#164]
<img width="1280" alt="screen shot 2017-08-28 at 2 38 49 pm" src="https://user-images.githubusercontent.com/2417632/29768422-c55bf278-8c03-11e7-902a-de86ee6bc266.png">

**Comment by vikasrohit** [comment]
Fixed. Should be in dev by EOD.

fyi, @fnisen

**Comment by fnisen** [comment]
@vikasrohit I couldn't test this in Dev. When I clicked on this link: https://accounts.topcoder-dev.com/member/reset-password?token=R87jKT&handle=beta_35, it redirected me here: https://accounts.topcoder-dev.com/member/reset-password. If it's fixed, I'll take your word for it.

**Comment by vikasrohit** [comment]
@fnisen It seems like we have some problem with cloud distribution for routing. If we use https://accounts.topcoder-dev.com/#!/member/reset-password?token=R87jKT&handle=beta_35 it works. It seems we have the same problem which had earlier which @mtwomey fixed. @mtwomey Can you please help us here again?

**Comment by fnisen** [comment]
Have pinged Matt on Slack to ask him to check it out.

**Comment by mtwomey** [comment]
@vikasrohit - I dont think this issue (see ^^^) with redirect is the same as last time (a cloud front configuration issue). I think it's something in the dev branch over the past couple of weeks (relating to the 301 redirect that happens). Could you please take a look?

**Comment by fnisen** [comment]
@vikasrohit looks like it's working now. I tested again just now and it worked correctly on both the member and connect sides, using incognito.

**Comment by vikasrohit** [comment]
Strange. What is making it behave like that. Anyway, if it is working fine now, it is good. Should we move changes to production?

**Comment by fnisen** [comment]
Yes, please go ahead.

**Comment by vikasrohit** [comment]
Verified on production. Closing.
