### ISSUE TITLE
Socail Sign up plugins are not working for new registration

### ISSUE THREAD

**Issue by m-yadav** [appirio-tech/accounts-app#218]
**Description**

Users are unable to register themselves using Social log in pluginns like Git, Google  or Facebook. They land upon the registartion page with details being filled but then the error pops up like below screenprint.

![image](https://user-images.githubusercontent.com/45197181/60262870-e0127f80-98fc-11e9-8732-e3a4db8a1574.png)

**Comment by m-yadav** [comment]
Below are the logs from the console when https://api.topcoder.com/v3/users is being hit.

{
  "id":"65bfbe6e:16b95f0fef9:f70",
  "result":{
      "success":true,
      "status":500,
      "metadata":null,
      "content":"User: **arn:aws:sts::409275337247:assumed-role/ecsInstanceRole/i-0729b7a892544573e is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:409275337247:table/Externals.Accounts (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: AccessDeniedException; Request ID: RPS8FMH3LEO106T169QFS9RCVBVV4KQNSO5AEMVJF66Q9ASUAAJG)**"},
      "version":"v3"
  
}

**Comment by sachin-maheshwari** [comment]
This should be fixed now. Last week (31-Aug-2019) we resolved dynamodb permission issue (not accessible from ECS cluster instance due to expired AWS access key) and redeploy the Identity service.
